# Generated by Django 5.2.4 on 2025-07-25 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='list_dae',
            new_name='list_date',
        ),
    ]
